# =============================================================================================== #
# Configuration for welcome - https://github.com/behaviorbot/welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening this issue, maintainers will get back to you as soon as possible!

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks so much for opening your first PR here!

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!

# =============================================================================================== #
# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: Need More Info

# *OPTIONAL* Add a list of people whose Issues/PRs will not be commented on
# keys must be GitHub usernames
requestInfoUserstoExclude:
  - 1v9
  - Acris
  - flashlab
  - geekrainy
  - iissnan
  - ivan-nginx
  - JiangTJ
  - LEAFERx
  - liolok
  - maple3142
  - Raincal
  - sli1989
  - stevenjoezhang
  - tsanie
  - wafer-li

# =============================================================================================== #
lockThreads:
  toxicityThreshold: .7
  numComments: 2
  setTimeInHours: 72
  replyComment: >
    This thread is being locked due to exceeding the toxicity minimums. cc/ @theme-next/next
