{% include 'baidu-push.swig' %}
{% include 'schedule.swig' %}
{% include 'math/index.swig' %}
{% include 'quicklink.swig' %}
{% include 'bookmark.swig' %}

{% include 'analytics/analytics-with-jquery.swig' %}
{% include 'facebook-sdk.swig' %}
{% include 'vkontakte-api.swig' %}
{% include 'rating.swig' %}

{% include 'search/index.swig' %}
{% include 'chat/index.swig' %}
{% include 'tags/index.swig' %}
