/* global hexo */
/**
 * Modify front-matter.
 *
 * Some key is included by hexo, please don't use it.
 * e.g. layout title date updated comments tags categories permalink keywords
 *
 * Some key is generated by hexo, don't use it too.
 * e.g. content excerpt more source full_source path permalink prev next raw photos link
 */

'use strict';

const keys = ['toc', 'reward_settings', 'wechat_subscriber'];

hexo.extend.filter.register('template_locals', (locals) => {
  const { page, theme } = locals;
  keys.forEach(key => {
    page[key] = Object.assign({}, theme[key], page[key]);
  });

  // Compatible
  if (page.reward !== undefined) {
    page.reward_settings.enable = page.reward;
    hexo.log.warn(`front-matter: reward has deprecated, path: ${page.path}`);
  }
  if (page.toc_number !== undefined) {
    page.toc.number = page.toc_number;
    hexo.log.warn(`front-matter: toc_number has deprecated, path: ${page.path}`);
  }
  if (page.toc_max_depth !== undefined) {
    page.toc.max_depth = page.toc_max_depth;
    hexo.log.warn(`front-matter: toc_max_depth has deprecated, path: ${page.path}`);
  }

  // Set default value for toc.max_depth
  if (!page.toc.max_depth) {
    page.toc.max_depth = 6;
  }
});
